[versions]
agp = "8.2.0"
hibernateCore = "5.6.5.Final"
kotlin = "1.9.20"
coreKtx = "1.12.0"
junit = "4.13.2"
minio = "8.5.9"
serialization = "1.6.3"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeCompiler = "1.5.11"
composeBom = "2024.04.00"
ktor = "2.3.10"
coroutines = "1.8.0"
navigation = "2.7.7"
koin = "3.5.4"
koin-ksp = "1.3.1"
datastore = "1.0.0"
okhhtpLogging = "4.12.0"
jwtParser = "0.12.5"
coil = "2.6.0"
spring = "2.7.18"
spring-dependency-management = "1.1.4"
springfoxSwagger2 = "2.9.2"
springfoxSwagger2Annotatios = "1.6.12"
apacheCommonsIo = "2.16.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
jwt-parser = { module = "io.jsonwebtoken:jjwt", version.ref = "jwtParser" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhhtpLogging" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
navigation-compose = { group = "androidx.navigation", name ="navigation-compose", version.ref = "navigation"}
koin-core = { group = "io.insert-koin", name = "koin-android", version.ref = "koin"}
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin"}
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }


spring-boot-starter-data = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
postges = { module = "org.postgresql:postgresql" }
hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernateCore" }
minio = { module = "io.minio:minio", version.ref = "minio" }
apache-commons-io = { module = "commons-io:commons-io", version.ref = "apacheCommonsIo" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-boot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging" }
springfox-swagger2 = { module = "io.springfox:springfox-swagger2", version.ref = "springfoxSwagger2" }
springfox-swagger2-ui = { module = "io.springfox:springfox-swagger-ui", version.ref = "springfoxSwagger2" }
springfox-swagger2-annotations = { module = "io.swagger:swagger-annotations", version.ref = "springfoxSwagger2Annotatios" }
springfox-swagger2-models = { module = "io.swagger:swagger-models", version.ref = "springfoxSwagger2Annotatios" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

spring-boot = {id = "org.springframework.boot", version.ref = "spring"}
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }


